---
grid_router_version: 1.4.0 # Install GridRouter version
grid_router_path: /etc/grid-router # Path to GridRouter
grid_router_qouta_path: /etc/grid-router/quota # Path to GridRouter quota
grid_router_qouta_user: selenoid # GridRouter quota user
grid_router_qouta_password: selenoid # GridRouter quota password
grid_router_time_zone: Europe/Moscow # Timezone in container
grid_router_port: 4444 # GridRouter port
grid_router_sctl_version: 1.2.0 # sctl version — https://github.com/seleniumkit/sctl/releases
grid_router_docker_api_version: 1.24 # Docker api version (for GridRouter)
grid_router_host_list: group # Host list for selenoid.xml

grid_router_regions: # Hosts list per region
    - name: "region-1"
      hosts:
        - name: localhost
          port: 4444
          browser_count: 4

grid_router_browsers: # Browser list usage selenoid
  - name: "firefox"
    defaultVersion: "54.0"
    versions:
      - "54.0"
      - "53.0"
      - "52.0"
  - name: "chrome"
    defaultVersion: "59.0"
    versions:
      - "59.0"
      - "58.0"
      - "57.0"
  - name: "opera"
    defaultVersion: "45.0"
    versions:
      - "45.0"
      - "44.0"
      - "43.0"
