---
- hosts: ggr
  vars:
    grid_router_version: 1.6.0
    grid_router_path: "{{ ansible_env.HOME }}/grid-router"
    grid_router_qouta_path: "{{ ansible_env.HOME }}/grid-router/quota"
    grid_router_port: 4445

    grid_router_regions:
      - name: "company"
        hosts:
          - name: 172.28.27.84
            port: 4444
            browser_count: 4
          - name: 172.28.27.89
            port: 4444
            browser_count: 4
          - name: 172.28.27.90
            port: 4444
            browser_count: 4
          - name: 172.28.27.65
            port: 4444
            browser_count: 4
          - name: 172.28.28.8
            port: 4444
            browser_count: 4
          - name: 172.28.28.76
            port: 4444
            browser_count: 4
          - name: 172.28.28.217
            port: 4444
            browser_count: 4

    grid_router_browsers:
      - name: "chrome"
        defaultVersion: "71.0"
        versions:
          - "71.0"
          - "72.0"
  roles:
    - gridrouter-docker

- hosts: selenoid-nodes
  vars:
    selenoid_version: 1.7.1
    selenoid_cm_version: 1.5.1
    selenoid_docker_api_version: 1.35
    selenoid_limit: 4
    selenoid_tmpfs: 512
    selenoid_timeout: 400s
    selenoid_config_dir: "{{ ansible_env.HOME }}/selenoid"
    selenoid_listen_port: 4444
    selenoid_browsers_last_versions: 3
    selenoid_browsers:
      - chrome
  roles:
    - selenoid-docker

