---
- hosts: ggr
  vars:
    grid_router_version: 1.7.1
    grid_router_ui_version: 1.1.2
    grid_router_path: "{{ ansible_env.HOME }}/grid-router"
    grid_router_qouta_path: "{{ ansible_env.HOME }}/grid-router/quota"
    grid_router_port: 4445
    selenoid_ui_version: 1.10.10
    selenoid_ui_port: 8080 

    grid_router_regions:
      - name: "company"
        hosts:
          - name: "{{ hostvars['selenoid1']['ansible_host'] }}"
            port: 4444
            browser_count: 4
          - name: "{{ hostvars['selenoid2']['ansible_host'] }}"
            port: 4444
            browser_count: 4  

    grid_router_browsers:
      - name: "chrome"
        defaultVersion: "118.0"
        versions:
          - "118.0"
          - "119.0"

  roles:
    - gridrouter-docker

- hosts: selenoid-nodes
  vars:
    selenoid_version: 1.10.10
    selenoid_cm_version: 1.8.5
    selenoid_docker_api_version: "1.42"
    selenoid_limit: 4
    selenoid_tmpfs: 512
    selenoid_timeout: 400s
    selenoid_config_dir: "{{ ansible_env.HOME }}/selenoid"
    selenoid_listen_port: 4444
    selenoid_browsers_last_versions: 2
    selenoid_browsers:
      - chrome
    selenoid_ui_version: 1.10.10
    selenoid_ui_port: 8080  
  roles:
    - selenoid-docker

- hosts: ggr
  tasks:
    - name: Print GGR host
      command: echo http://{{ hostvars['ggr']['ansible_host'] }}:8080
      delegate_to: ggr
      register: grid_router_host

    - debug:
        var: grid_router_host.stdout_lines   
    
    - name: Check grid-router status
      command: "curl -s http://{{ hostvars['ggr']['ansible_host'] }}:8888/status"
      delegate_to: ggr
      ignore_errors: yes
      register: grid_router_status

    - debug:
        var: grid_router_status.stdout_lines    

