---
- name: Install required system packages
  become: yes
  become_user: root
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Install required packages
  become: yes
  become_user: root
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip
    - docker.io
  ignore_errors: yes

- name: Selenoid | Install python modules for Docker
  pip:
    name: "{{ item.name }}"
  with_items:
    - { name: docker }

- name: Selenoid | Check if Docker is running and get container ID for selenoid and cm
  become: yes
  become_user: root
  command: docker ps -aq --filter "name=selenoid" --filter "name=cm"
  register: selenoid_container_id
  ignore_errors: yes

- name: Selenoid | Remove selenoid container if it exists
  become: yes
  become_user: root
  shell: 'docker stop {{ item }} && docker rm -fv {{ item }}'
  with_items: "{{ selenoid_container_id.stdout_lines | default([]) }}"
  when: selenoid_container_id.stdout_lines | default([]) | length > 0

- name: Download Configuration Manager
  become: yes
  become_user: root
  raw: wget -O /usr/bin/cm "https://github.com/aerokube/cm/releases/download/{{ selenoid_cm_version }}/cm_linux_amd64"

- name: Get Access to Configuration Manager
  become: yes
  become_user: root
  raw: chmod +x /usr/bin/cm

- name: Install Selenoid
  become: yes
  become_user: root
  raw: /usr/bin/cm selenoid start selenoid start
      --version {{ selenoid_version }}
      --tmpfs {{ selenoid_tmpfs }}
      --env DOCKER_API_VERSION={{ selenoid_docker_api_version }}
      --browsers {% for browser in selenoid_browsers -%}{{ browser }}{%- if not loop.last -%},{%- endif -%}{%- endfor %}
      --last-versions {{ selenoid_browsers_last_versions }}
      --force
      --vnc
      --args "-limit {{ selenoid_limit }} -listen :{{ selenoid_listen_port }} -timeout {{ selenoid_timeout }} -disable-queue"

- name: Install Selenoid UI
  become: yes
  become_user: root
  raw: /usr/bin/cm selenoid-ui start --version {{ selenoid_ui_version }}
      