---
- name: Selenoid | Install certain python modules for docker
  pip:
    name: "{{ item.name }}"
  with_items:
    - { name: docker-py }

- name: Selenoid | Check selenoid container exist
  shell: 'docker ps -aq --filter "name={{ item }}"'
  with_items:
    - 'selenoid'
  register: found_containers

- name: Selenoid | Remove selenoid container if exist
  shell: 'docker stop {{ item.item }} && docker rm -fv {{ item.item }}'
  with_items: '{{ found_containers.results }}'
  when: item.stdout

- name: Selenoid | Run CM container, download browser images and run selenoid
  docker_container:
    name: cm
    image: "aerokube/cm:{{ selenoid_cm_version }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ selenoid_config_dir }}:/root"
    env:
      TZ: "{{ selenoid_time_zone }}"
      OVERRIDE_HOME: "{{ selenoid_config_dir }}"
      DOCKER_API_VERSION: "{{ selenoid_docker_api_version }}"
    command: >
      selenoid start
        --version {{ selenoid_version }}
        --tmpfs {{ selenoid_tmpfs }}
        --env DOCKER_API_VERSION={{ selenoid_docker_api_version }}
        --browsers {% for browser in selenoid_browsers -%}{{ browser }}{%- if not loop.last -%},{%- endif -%}{%- endfor %}
        --last-versions {{ selenoid_browsers_last_versions }}
        --force
        --vnc
        --args "-limit {{ selenoid_limit }} -listen :{{ selenoid_listen_port }} -timeout {{ selenoid_timeout }} -disable-queue"